name: SpawnAid
version: '${version}'
main: net.labindustries.spawnaid.SpawnAid
api-version: 1.19
authors: [ Lukas02 ]
description: A spawn plugin
website: labindustries.net
commands:
  setspawn:
    description: Set the spawn point
  spawn:
    description: Teleport a player at the spawn location
